// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLjMbwAUQwv5WKQetmI7bFG92MCAYpN-Y',
    appId: '1:286252921212:web:7c5bfcb73cbf57e4d4b4f9',
    messagingSenderId: '286252921212',
    projectId: 'pln-jagagrid-97b30',
    authDomain: 'pln-jagagrid-97b30.firebaseapp.com',
  storageBucket: 'pln-jagagrid-97b30.appspot.com',
    measurementId: 'G-TEZECWFRXQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBosTSQQM62y924DdELq_5r8IWmHeyrzUE',
    appId: '1:286252921212:android:2cf0fda04f90b451d4b4f9',
    messagingSenderId: '286252921212',
    projectId: 'pln-jagagrid-97b30',
  storageBucket: 'pln-jagagrid-97b30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCL0oPbyeHJiFvwDGupZcrFzvRh9ONBpCM',
    appId: '1:286252921212:ios:b4e40a3d0926cfa3d4b4f9',
    messagingSenderId: '286252921212',
    projectId: 'pln-jagagrid-97b30',
  storageBucket: 'pln-jagagrid-97b30.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCL0oPbyeHJiFvwDGupZcrFzvRh9ONBpCM',
    appId: '1:286252921212:ios:b4e40a3d0926cfa3d4b4f9',
    messagingSenderId: '286252921212',
    projectId: 'pln-jagagrid-97b30',
  storageBucket: 'pln-jagagrid-97b30.appspot.com',
    iosBundleId: 'com.example.flutterApplication2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLjMbwAUQwv5WKQetmI7bFG92MCAYpN-Y',
    appId: '1:286252921212:web:b1b302d6f161a9d2d4b4f9',
    messagingSenderId: '286252921212',
    projectId: 'pln-jagagrid-97b30',
    authDomain: 'pln-jagagrid-97b30.firebaseapp.com',
  storageBucket: 'pln-jagagrid-97b30.appspot.com',
    measurementId: 'G-WS933HBLE8',
  );

}